const { readJSONSync, writeJSONSync, writeFileSync, readFileSync, existsSync, mkdirSync } = require('fs-extra');
const { relative, join } = require('path');
const compiler = require('jsx-compiler');

function createImportStatement(req) {
  return `import '${req}';`;
}

function generateDependencies(dependencies) {
  return Object
    .keys(dependencies)
    .map((mod => createImportStatement(mod)))
    .join('\n');
}

module.exports = function appLoader(content) {
  const rawContent = readFileSync(this.resourcePath, 'utf-8');
  const config = readJSONSync(join(this.rootContext, 'app.json'));
  const compilerOptions = Object.assign({}, compiler.baseOptions, {
    filePath: this.resourcePath,
    type: 'app',
  });
  const transformed = compiler(rawContent, compilerOptions);

  const distPath = this._compiler.outputPath;
  if (!existsSync(distPath)) mkdirSync(distPath);

  const relativeSourcePath = relative(this.rootContext, this.resourcePath);
  const targetFilePath = join(distPath, relativeSourcePath);

  this.addDependency(join(this.rootContext, 'app.json'));

  const transformedAppConfig = transformAppConfig(config);
  writeFileSync(join(distPath, 'app.js'), transformed.code);
  writeJSONSync(join(distPath, 'app.json'), transformedAppConfig, { spaces: 2 });

  if (transformed.style) {
    writeFileSync(join(distPath, 'app.acss'), transformed.style);
  }

  return [
    `/* Generated by JSX2MP AppLoader, sourceFile: ${this.resourcePath}. */`,
    generateDependencies(transformed.imported),
  ].join('\n');
}

function transformAppConfig(originalConfig) {
  const config = {};
  for (let key in originalConfig) {
    const value = originalConfig[key];
    switch (key) {
      case 'routes':
        const pages = [];
        if (Array.isArray(value)) {
          // only resolve first level of routes.
          value.forEach(({ path, component }) => {
            pages.push(component);
          });
        }
        config.pages = pages;
        break;

      default:
        config[key] = value; break;
    }
  }

  return config;
}
