const { readJSONSync, writeJSONSync, writeFileSync, readFileSync, existsSync, mkdirSync } = require('fs-extra');
const { join } = require('path');
const compiler = require('jsx-compiler');
const { getOptions } = require('loader-utils');
const moduleResolve = require('./utils/moduleResolve');
const { removeExt } = require('./utils/pathHelper');
const defaultStyle = require('./defaultStyle');


function createImportStatement(req) {
  return `import '${req}';`;
}

function generateDependencies(dependencies) {
  return Object
    .keys(dependencies)
    .map(mod => createImportStatement(mod))
    .join('\n');
}

function getRelativePath(filePath) {
  let relativePath;
  if (filePath[0] === '/') {
    relativePath = `.${filePath}`;
  } else if (filePath[0] === '.') {
    relativePath = filePath;
  } else {
    relativePath = `./${filePath}`;
  }
  return relativePath;
}

module.exports = function appLoader(content) {
  const loaderOptions = getOptions(this);
  const { entryPath } = loaderOptions;
  const appConfigPath = removeExt(this.resourcePath) + '.json';
  const rawContent = readFileSync(this.resourcePath, 'utf-8');
  const config = readJSONSync(appConfigPath);

  const outputPath = this._compiler.outputPath;
  if (!existsSync(outputPath)) mkdirSync(outputPath);

  const sourcePath = join(this.rootContext, entryPath);

  const compilerOptions = Object.assign({}, compiler.baseOptions, {
    resourcePath: this.resourcePath,
    outputPath,
    sourcePath,
    type: 'app',
  });
  const transformed = compiler(rawContent, compilerOptions);

  this.addDependency(appConfigPath);

  const transformedAppConfig = transformAppConfig(entryPath, config);
  writeFileSync(join(outputPath, 'app.js'), transformed.code);
  writeJSONSync(join(outputPath, 'app.json'), transformedAppConfig, { spaces: 2 });
  // Write app.raw.json for route information.
  writeJSONSync(join(outputPath, 'app.raw.json'), config, { spaces: 2 });

  const appCssPath = join(outputPath, 'app.acss');
  const appCss = transformed.style ? defaultStyle + transformed.style : defaultStyle;
  writeFileSync(appCssPath, appCss);

  return [
    `/* Generated by JSX2MP AppLoader, sourceFile: ${this.resourcePath}. */`,
    generateDependencies(transformed.imported),
  ].join('\n');
};

function transformAppConfig(entryPath, originalConfig) {
  const config = {};
  for (let key in originalConfig) {
    const value = originalConfig[key];

    switch (key) {
      case 'routes':
        const pages = [];
        if (Array.isArray(value)) {
          // Only resolve first level of routes.
          value.forEach(({ component, source }) => {
            // Compatible with old version definition of `component`.
            pages.push(moduleResolve(entryPath, getRelativePath(source || component)));
          });
        }
        config.pages = pages;
        break;

      default:
        config[key] = value;
        break;
    }
  }

  return config;
}
