export default {
  ali: {
    xml: 'axml',
    css: 'acss',
    if: 'a:if',
    else: 'a:else',
    elseif: 'a:elif',
    for: 'a:for',
    forItem: 'a:for-item',
    forIndex: 'a:for-index',
    key: 'a:key',
    tap: 'onTap',
    touchStart: 'onTouchStart',
    touchMove: 'onTouchMove',
    touchEnd: 'onTouchEnd',
    touchCancel: 'onTouchCancel',
    load: 'onLoad',
    error: 'onError',
    supportComponentGenerics: false
  },
  wechat: {
    xml: 'wxml',
    css: 'wxss',
    if: 'wx:if',
    else: 'wx:else',
    elseif: 'wx:elif',
    for: 'wx:for',
    forItem: 'wx:for-item',
    forIndex: 'wx:for-index',
    key: 'wx:key',
    tap: 'bindtap',
    touchStart: 'bindtouchstart',
    touchMove: 'bindtouchmove',
    touchEnd: 'bindtouchend',
    touchCancel: 'bindtouchcancel',
    load: 'bindload',
    error: 'binderror',
    supportComponentGenerics: true
  }
};
